name: SonarCloud Analysis for AWS SDK Java v2
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Untuk memungkinkan menjalankan workflow secara manual

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disarankan untuk SonarCloud untuk mendapatkan full git history
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Create sonar-project.properties
        run: |
          cat > sonar-project.properties << EOF
          sonar.projectKey=dc6a14762cab506ad576525ecce727d6af482711
          sonar.organization=shikitoka123
          
          # Pengaturan direktori sumber
          sonar.sources=src
          
          # Pengaturan direktori test berdasarkan struktur yang terlihat
          sonar.tests=test
          
          # Pengaturan exclusions dan inclusions
          sonar.exclusions=**/target/**/*,**/.git/**/*,**/resources/**/*,**/pom.xml
          sonar.test.inclusions=**/*Test.java,**/*Tests.java
          
          # Konfigurasi untuk Java
          sonar.java.source=1.8
          sonar.java.libraries=.
          
          # Abaikan error kompilasi
          sonar.java.skipCompile=true
          
          # Untuk memastikan Sonar dapat mendeteksi semua file
          sonar.sourceEncoding=UTF-8
          EOF
      
      # Menjalankan SonarScanner langsung
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}